Oe 660/pw borrow read return books
NYPL/ereading-clients pull request #508
Opened 2022-10-31 20:10 UTC by ayan1229

2022-10-31 23:13 UTC, ayan1229 commented
hi @samanthaandrews 
test is failing due to read-return bug in staging.

2022-11-01 15:26 UTC, samanthaandrews requested changes
A few changes to make before we can merge this. it's looking really good!

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/support/mappings.ts
> +    regex: /^\/app\/book\//,
We should change this regex to the full path including `https%3A%2F%2Fqa-circulation.openebooks.us%2FUSOEI%2Fworks%2FAxis%2520360%2520ID%2F0017370149`

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/support/mappings.ts
> +  "borrowed book detail": {
Consider adding the title of the book to this string so that we know which book it maps to

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/features/circulationPage.feature
>      And the "middle grades header" should be displayed
It seems like this "middle grades header" should also change to "middle grades header for all access user" to match the others

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/tests/assertions.spec.ts
> +    console.log("we are here !!!");
Remove stray console.log

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/tests/assertions.spec.ts
>  Given(
I think this is missing an `expect`. Should be `expect(this.page.locator(element)).isEnabled();`

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/tests/assertions.spec.ts
> +Then(/^I verify "([^"]*)" is displayed$/, async function (this: CustomWorld) {
Since this Then statement is specific to the borrow button, I don't think we should pass in a string here at all. It should just directly say "I verify the borrow this book button is displayed" so that we don't get confused and try to use this assertion outside the context of verifying the borrow a book button.

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/tests/assertions.spec.ts
>  Given(
We should verify that we're not missing any `expect` values throughout all of these tests, just to be sure

2022-11-01 15:26 UTC, samanthaandrews commented on playwright/support/mappings.ts
> +  "e-reader toggle window button": "//header/div[1]/button[3]",
This selector seems pretty brittle since it relies on the position of the div and the buttons. I think this button includes the text "Toggle Fullscreen" that you should be able to use instead.

2022-12-06 18:58 UTC, closed without merging