OE-764: Fix navigation function in playwright (clever login failure)
NYPL/ereading-clients pull request #548
Opened 2022-12-16 02:04 UTC by ayan1229

2022-12-16 20:41 UTC, samanthaandrews requested changes
Just one small change, otherwise this looks good. You'll also need to fix merge conflicts in the CHANGELOG.md file.

2022-12-16 20:41 UTC, samanthaandrews commented on apps/oew/playwright/features/cleverSignIn.feature
>       And I click the "sign out button"
Let's add a step here to confirm that after logging in with Clever, they see the Circulation landing page

2022-12-17 16:06 UTC, samanthaandrews approved these changes

2022-12-20 10:44 UTC, kristojorg commented
Is this ready to merge?

2022-12-20 13:51 UTC, samanthaandrews commented
yeah it’s ready

2022-12-20 13:52 UTC, merged