OE-753: Configure Jest & Playwright in OEH & add to CI/CD
NYPL/ereading-clients pull request #558
Opened 2022-12-23 23:28 UTC by samanthaandrews

To do:
- [ ] Setup Jest to run in OEH & write a simple test to make sure it works
- [ ] Setup Playwright to bypass login using `storageState.json`
- [ ] Setup playwright-msw to intercept requests & write tests to demonstrate how to override the default handlers
- [ ] Add GH Actions script to enable OEH Playwright tests on push events
- [ ] Update README with information about unit tests and integration tests
- [ ] Move `msw/fixtures/*` to a shared package

2022-12-24 02:00 UTC, samanthaandrews commented
In the TAD I suggested we use Appium & Webdriver for end-to-end tests on emulated iOS and Android devices https://docs.google.com/document/d/1OP9vD78IxtP-S3LVwUvFFx-ZHtw8J20MqCUbgwu1GPs/edit#heading=h.ex89zp9b41n

@Toxiapo @kristojorg @oliviawongnyc I'm wondering if y'all think we should implement this now or wait for a later milestone? It seems like the [`ionic-e2e-example`](https://github.com/ionic-team/ionic-e2e-example) app is an _alpha_ example, which means it might take some time to ensure we can configure it to work correctly. I'm happy to try though!

Ionic does say that they are working to implement end-to-end testing within Appflow in the future, but who knows when that will actually happen.

2022-12-30 13:24 UTC, kristojorg commented
@samanthaandrews I think we can wait until a future milestone to implement e2e testing on real mobile devices. We can, however, have browser-based e2e testing using eg playwright now

2022-12-30 21:56 UTC, Toxiapo commented
@samanthaandrews I think waiting for a later milestone and just focusing on the setup, for now, is fine. And start writing tests in the next milestone

2022-12-30 22:09 UTC, samanthaandrews commented
> @samanthaandrews I think we can wait until a future milestone to implement e2e testing on real mobile devices. We can, however, have browser-based e2e testing using eg playwright now

Cool, thanks, y'all. I added an item to the OEH tech debt document reflecting that this is something we want to do for a future milestone: https://docs.google.com/document/d/13FDnaocXpsQrXdFtUQ_Tkl2kKpP1S9HczZk2jvEgTpg/edit#heading=h.jhcqi3786f5f

This PR is ready for review whenever y'all get to it next week.

2023-01-03 21:35 UTC, Toxiapo requested changes
Just a few comments otherwise this looks good to me

2023-01-03 21:35 UTC, Toxiapo commented on .github/workflows/oeh-integration-playwright.yml
> +
I think @kristojorg mentioned on one of the PRs that we can use cache on this to speed up the install process? `with: cache: 'npm'`

2023-01-03 21:35 UTC, Toxiapo commented on .github/workflows/oew-e2e-playwright.yml
> +    if: github.event.deployment_status.environment == 'open-ebooks-web' && github.event.deployment_status.state == 'success'
I think the full environment name was something like 'Preview - open-ebooks-web', so this will always evaluate as false.

2023-01-03 21:35 UTC, Toxiapo commented on apps/oeh/README.md
> +
I think since this README is in the 'oeh' workspace, we can omit `-w oeh` from the command, just to match the guidelines described in the above sections

2023-01-03 21:35 UTC, Toxiapo commented on apps/oeh/README.md
>  # Notes
nit: hanging heading without contents

2023-01-03 21:35 UTC, Toxiapo commented on apps/oeh/playwright.config.ts
> +// require('dotenv').config();
nit: I guess we don't need this package anymore?

2023-01-03 21:35 UTC, Toxiapo commented on apps/oeh/playwright.config.ts
> +    }
Question: These are phone browsers only, are the web-based browser default runners for the tests?

2023-01-03 21:35 UTC, Toxiapo commented on apps/oeh/src/test-utils/index.tsx
> +type CustomRenderOptions = Parameters<typeof render>[1] & {
I am curious about what this notion means. `Parameters<typeof render>[1]`

2023-01-03 21:39 UTC, Toxiapo commented on apps/oeh/playwright.config.ts
> +    }
oh wait, this is for hybrid. Please ignore me... 😅

2023-01-04 03:39 UTC, samanthaandrews commented on .github/workflows/oeh-integration-playwright.yml
> +
good catch! you're right

2023-01-04 03:39 UTC, samanthaandrews commented on .github/workflows/oew-e2e-playwright.yml
> +    if: github.event.deployment_status.environment == 'open-ebooks-web' && github.event.deployment_status.state == 'success'
thank you. reverting to what you had previously used!

2023-01-04 03:40 UTC, samanthaandrews commented on apps/oeh/README.md
> +
good idea

2023-01-04 03:41 UTC, samanthaandrews commented on apps/oeh/README.md
>  # Notes
i think this is just the header `# Notes` and then there are subheadings beneath with content

2023-01-04 03:43 UTC, samanthaandrews commented on apps/oeh/playwright.config.ts
> +// require('dotenv').config();
yup. i think playwright added this automatically when i ran the helper `npx playwright init` to set up this file. removing that section for now!

2023-01-04 03:46 UTC, samanthaandrews commented on apps/oeh/src/test-utils/index.tsx
> +type CustomRenderOptions = Parameters<typeof render>[1] & {
honestly i copied this from oew `test-utils` and it wasn't clear to me. looks like it's not even necessary so i removed it. good catch!

2023-01-04 15:35 UTC, Toxiapo approved these changes
LGTM!

2023-01-04 16:51 UTC, merged