OE-776: Add collection page and view more button
NYPL/ereading-clients pull request #574
Opened 2023-01-13 20:51 UTC by Toxiapo

2023-01-17 19:38 UTC, Toxiapo commented on apps/oeh/src/App.tsx
> +import "./theme/global.css";
I created this global style just so I can avoid adding `ion-text-center` to multiple components, we can put our global CSS here until we decide which styling route we should go with.

2023-01-17 19:41 UTC, Toxiapo commented on apps/oeh/src/App.tsx
> +          exact
This is needed for the dynamic route mainly because the collection page shares the `/app/browse` path with the browse page.

2023-01-19 14:58 UTC, kristojorg commented on apps/oeh/src/App.tsx
> +import "./theme/global.css";
I think we've decided right? AFAIK we are using CSS files and the [ionic css utilities](https://ionicframework.com/docs/layout/css-utilities). Either way I think this is okay

2023-01-19 14:58 UTC, kristojorg commented on apps/oeh/src/App.tsx
> +import "./theme/global.css";
Although maybe the utilities have this built in?

2023-01-19 15:00 UTC, kristojorg commented
> the  /app/browse/collection/book/:bookUrl route renders the book detail page from the collection page.

Is this necessary? We have the `/app/browse/book/:bookUrl` route already which seems like the same thing no? I think it's okay to route from `/app/browse/collection/:collectionUrl` to `/app/browse/book/:bookUrl`, just not to a different tab like `/app/loans`

2023-01-19 15:07 UTC, kristojorg reviewed
Just some questions

2023-01-19 15:07 UTC, kristojorg commented on apps/oeh/src/App.tsx
> +import "./theme/global.css";
I guess we could set up some css files for things like global changes and updates to the ionic theme

2023-01-19 15:07 UTC, kristojorg commented on apps/oeh/src/App.tsx
> +          exact
Strange. I don't have a problem with it but it doesn't seem necessary, then `/app/browse/book/:bookUrl` also shares that but it doesn't have `exact`

2023-01-19 15:07 UTC, kristojorg commented on apps/oeh/src/pages/Collection.tsx
> +function getRoutePath(path: string): string {
A comment would be helpful here

2023-01-19 21:51 UTC, Toxiapo commented on apps/oeh/src/theme/global.css
> +    text-align: center;
The default align was align-left. 

Ah okay, so it's pushed toward the right because of the back button, I will update the css

2023-01-19 22:14 UTC, Toxiapo commented on apps/oeh/src/App.tsx
> +          exact
The problem was that if I were on the `browse` page, and clicked on a book, it would render the detail page. But if I go to a sub-lane (collection page) and visit the book detail page from there, I can see the URL updates, but it doesn't render the content for me. I've tried many things, but only this method worked for me..

2023-01-19 22:18 UTC, Toxiapo commented on apps/oeh/src/pages/Collection.tsx
> +function getRoutePath(path: string): string {
This is to extract the collection URL and remove the ID part, but I can probably just remove this and hardcode that URL since it should always render the collection page.

2023-01-19 22:21 UTC, Toxiapo commented on apps/oeh/src/App.tsx
> +import "./theme/global.css";
Agree. I can do some research on how to utilize ionic CSS best. Maybe an `override.css` is a better fit if we are going to manipulate their default CSS

2023-01-24 15:20 UTC, kristojorg commented on apps/oeh/src/theme/global.css
> +    text-align: center;
I think honestly I would leave it to the platform defaults since I believe it is specific to each platform

2023-01-24 15:29 UTC, kristojorg requested changes
Just a few questions

2023-01-24 15:29 UTC, kristojorg commented on apps/oeh/src/App.tsx
> +          exact
Strange, but sounds good! Thanks for the explanation : )

2023-01-24 15:29 UTC, kristojorg commented on apps/oeh/src/theme/global.css
> +  text-align: center;
At the moment, I think we should leave this as-is for a few reasons:
1. We aren't trying to match designs exactly yet, just get wireframes in place
2. This will update all titles in the app
3. This is applied for both platforms, and I believe the behavior differs for them currently

2023-01-24 15:29 UTC, kristojorg commented on apps/oeh/src/pages/Browse.tsx
> +            baseUrl={match.url + "/collection"}
It looks like the `baseUrl` is now always `/app/browse/collection` right? Can we remove it?

2023-01-24 18:55 UTC, samanthaandrews commented on apps/oeh/src/pages/Collection.tsx
> +  async function doRefresh(event: CustomEvent<RefresherEventDetail>) {
might want to rename this or add a comment specifying what we are refreshing here

2023-01-24 20:31 UTC, Toxiapo commented on apps/oeh/src/pages/Browse.tsx
> +            baseUrl={match.url + "/collection"}
We do need it because that's being used for the `view more` link. Do you think it makes sense to just remove the /app/browse route and replace it with just the /app/collection route then?

2023-01-24 21:21 UTC, Toxiapo commented on apps/oeh/src/theme/global.css
> +  text-align: center;
Ok, yea that makes sense! I missed the cross-platform style. I am just going to remove this for this PR.

2023-01-24 22:32 UTC, Toxiapo commented on apps/oeh/src/pages/Browse.tsx
> +            baseUrl={match.url + "/collection"}
OK, I updated the route to use `/app/collection` as our main entry page, and removed `/app/browse`. I think this may be easier for our mental model since this would be a similar setup as OEW. Let me know what you think!

2023-02-02 15:53 UTC, samanthaandrews commented
Let's try to merge this one today or tomorrow if possible!

2023-02-03 14:59 UTC, kristojorg commented on apps/oeh/src/pages/Browse.tsx
> +            baseUrl={match.url + "/collection"}
That is a great idea, thanks!

2023-02-03 15:41 UTC, kristojorg reviewed
This looks great, just the one question about the url segments. @Toxiapo and I discussed this on slack but I think it makes sense to have a url segment named per tab, and then sub segments describe the views within the tab. So we would have:

- /app/browse
  - /collection/:collectionUrl
  - /book/:bookUrl
- /app/settings
- /app/my-books
  - /book/:bookUrl
- /app/read

We may want to change /browse to /all-books if we decide that is what we are going to name that tab. That way all the tabs will have a url segment that match

2023-02-03 21:41 UTC, kristojorg approved these changes
Looks good to me!

2023-02-08 15:32 UTC, merged