OE-825: Add infinite scrolling
NYPL/ereading-clients pull request #592
Opened 2023-01-25 22:18 UTC by Toxiapo

2023-02-01 19:47 UTC, samanthaandrews requested changes
Just one small thing, otherwise this looks great!

2023-02-01 19:47 UTC, samanthaandrews commented on apps/oeh/src/components/Collection/BookListView.tsx
> +  const isFetchingMore = !!(!error && hasMore && size > (data?.length ?? 0));
I like how concise this is but it is also hard to read. Can we make it slightly more verbose and increase readability for future us?

2023-02-01 19:47 UTC, samanthaandrews commented on apps/oeh/src/components/Collection/BookListView.tsx
> +const getFetchKey = (collectionUrl: string, token: string | undefined) => {
nice!

2023-02-01 19:49 UTC, samanthaandrews commented
@Toxiapo If you pull in `main` then I think that `OEW E2E Playwright Test` CI check should go away. I changed those tests a few weeks ago to only run on a daily cron.

Not sure why the OEH Playwright test failed...

2023-02-06 15:28 UTC, Toxiapo commented on apps/oeh/src/components/Collection/BookListView.tsx
> +  const isFetchingMore = !!(!error && hasMore && size > (data?.length ?? 0));
I added some comments, let me know if this is better!

2023-02-06 19:50 UTC, Toxiapo commented
> @Toxiapo If you pull in `main` then I think that `OEW E2E Playwright Test` CI check should go away. I changed those tests a few weeks ago to only run on a daily cron.
> 
> Not sure why the OEH Playwright test failed...

Yup, it looks like that fixes the issue. Thanks! @samanthaandrews

2023-02-08 16:18 UTC, kristojorg approved these changes
Looks great!

2023-02-08 16:18 UTC, kristojorg commented on apps/oeh/src/chakra/components/BookCard.tsx
> +  const bookHref = `${getRootRoute(baseUrl)}/book/${encodedBookUrl}`;
Might be easier to remove these changes or they will conflict with my changes using `useTabPath`. You could also rebase this on top of your other PR to bring those changes in if you want

2023-02-08 16:18 UTC, kristojorg commented on apps/oeh/src/components/Collection/BookListView.tsx
> +    ) ?? [];
This formatting seems odd, did prettier get to run on this file?

2023-02-09 18:13 UTC, Toxiapo commented on apps/oeh/src/chakra/components/BookCard.tsx
> +  const bookHref = `${getRootRoute(baseUrl)}/book/${encodedBookUrl}`;
Good idea!

2023-02-09 18:15 UTC, Toxiapo commented on apps/oeh/src/components/Collection/BookListView.tsx
> +    ) ?? [];
It does seem odd, but somehow the prettier likes this format 🤨

2023-02-15 16:44 UTC, samanthaandrews approved these changes
🚀

2023-02-21 15:11 UTC, samanthaandrews commented
@Toxiapo Lmk if i can merge this today

2023-02-21 16:10 UTC, Toxiapo commented
Good to go!

2023-02-21 16:11 UTC, merged