Upgrades web-reader package to ^4.0.0
NYPL/ereading-clients pull request #597
Opened 2023-02-01 21:56 UTC by oliviawongnyc

- Updates @nypl/web-reader version from ^3.2.5 to ^4.0.0 to include latest updates to Settings Panel

2023-02-02 14:24 UTC, Toxiapo requested changes
Hmm, the scrolling function seems fine to me. I tested the `Lost Brother -  Dixon, Franklin W.` book.

2023-02-02 14:24 UTC, Toxiapo commented on apps/oew/package.json
> +    "@nypl/web-reader": "^4.0.0",
I am curious why we are updating this to 4.0.0 instead of 4.2.0?

2023-02-02 14:31 UTC, oliviawongnyc commented on apps/oew/package.json
> +    "@nypl/web-reader": "^4.0.0",
With the caret, this installs 4.2.0. But I am open to changing it to be more explicit if people prefer!

2023-02-02 14:36 UTC, oliviawongnyc commented on apps/oew/package.json
> +    "@nypl/web-reader": "^4.0.0",
My thinking was that the only guaranteed number when using the caret is the major version. If we are explicit about ^4.2.0, the dev doesn't know if the minor version is what is installed or if that is outdated so why include it. But I def don't feel strongly about it, and happy to change if it's clearer to the team!

2023-02-02 14:40 UTC, oliviawongnyc commented
> Hmm, the scrolling function seems fine to me. I tested the `Lost Brother - Dixon, Franklin W.` book.

@Toxiapo, interesting! This is for me on Chrome Version 109.0.5414.119:

https://user-images.githubusercontent.com/57868332/216354507-5ff7f33c-c3b9-4f91-a236-f6ea7a0b0a23.mov

2023-02-02 17:16 UTC, Toxiapo commented
> > Hmm, the scrolling function seems fine to me. I tested the `Lost Brother - Dixon, Franklin W.` book.
> 
> @Toxiapo, interesting! This is for me on Chrome Version 109.0.5414.119:
> 
>  Screen.Recording.2023-02-02.at.9.38.43.AM.mov

Ah okay. I believe the pages you were viewing were meant to be a single-page resource that's why you can't scroll. It's only scrollable when a resource was broken down into smaller frames and can't be fully displayed by the current viewport.

2023-02-02 18:04 UTC, Toxiapo approved these changes
This looks good to me!

2023-02-03 17:08 UTC, oliviawongnyc commented
> > > Hmm, the scrolling function seems fine to me. I tested the `Lost Brother - Dixon, Franklin W.` book.
> > 
> > 
> > @Toxiapo, interesting! This is for me on Chrome Version 109.0.5414.119:
> > Screen.Recording.2023-02-02.at.9.38.43.AM.mov
> 
> Ah okay. I believe the pages you were viewing were meant to be a single-page resource that's why you can't scroll. It's only scrollable when a resource was broken down into smaller frames and can't be fully displayed by the current viewport.

I see, so if I had kept going, I would have been able to see the pagination? I wonder if it would make sense to disable the pagination button unless it was available.

2023-02-06 16:58 UTC, samanthaandrews commented
@oliviawongnyc The behavior you described is intentional, but I agree it is not intuitive. Basically, even in scrolling mode, single-page resources are still paginated and display the "prev" and "next" buttons. Once you navigate to a longer chapter, you will be able to scroll. Then, once you reach the end of that chapter, you have to paginate to the next chapter.

For now, I think this is good to go to Jennifer for VQA (maybe you've already done this!). Addressing the scrolling vs pagination UX can be addressed in a separate initiative.

2023-02-08 16:22 UTC, kristojorg approved these changes
Sweet!

2023-02-09 14:11 UTC, merged