OE-852/Contact_Form_Testing
NYPL/ereading-clients pull request #605
Opened 2023-02-13 11:31 UTC by ayan1229

2023-02-13 16:51 UTC, Toxiapo commented on apps/oew/playwright/support/mappings.ts
> +  "contact page dropdown": "//select[@id='field-:R1db8nl6:']",
Is this a selector ID from chakra components, or it's a playwright config? I wonder if there's a way to select by text or label like how you did it for the other inputs.

2023-02-13 16:56 UTC, ayan1229 commented on apps/oew/playwright/support/mappings.ts
> +  "contact page dropdown": "//select[@id='field-:R1db8nl6:']",
@Toxiapo , I can change it to "//select[@name='inquriy']"

2023-02-13 17:02 UTC, Toxiapo commented on apps/oew/playwright/support/mappings.ts
> +  "contact page dropdown": "//select[@id='field-:R1db8nl6:']",
Superb, Thank you!

2023-02-13 17:40 UTC, samanthaandrews requested changes
Just a couple of small changes!

2023-02-13 17:40 UTC, samanthaandrews commented on apps/oew/playwright/features/contact-form-submit.feature
> +    Scenario: As a user I should be able to fill up the contact form with my informations and contact NYPL Open ebook Team
Thank you this is great!

2023-02-13 17:53 UTC, ayan1229 commented on apps/oew/playwright/tests/click.spec.ts
> +    if(contactDropdown === null) {
This was used because typescript check was throwing an error that said that using this might return null

2023-02-13 17:55 UTC, ayan1229 commented on apps/oew/playwright/support/mappings.ts
> +  "contact page dropdown": "//select[@id='field-:R1db8nl6:']",
changed it to  "//select[@name='inquiry']"

2023-02-13 18:07 UTC, ayan1229 commented on apps/oew/playwright/tests/click.spec.ts
> +    if(contactDropdown === null) {
you know what, I have updated VS code and now not getting error. Removed the condition

2023-02-13 18:10 UTC, ayan1229 commented on apps/oew/playwright/features/contact-form-submit.feature
> +    Scenario: As a user I should be able to fill up the contact form with my informations and contact NYPL Open ebook Team
🙏

2023-02-13 18:14 UTC, samanthaandrews commented on apps/oew/playwright/tests/click.spec.ts
> +    const element = elements[elementKey];
we actually don't need this `const`. the `elements["contact dropdown"]` below is referencing the mappings file item that we need. so just remove line 16 and this looks good to me!

2023-02-13 18:14 UTC, samanthaandrews approved these changes
Just remove that unused `const` and this can be merged 👍

2023-02-13 18:20 UTC, ayan1229 commented on apps/oew/playwright/tests/click.spec.ts
> +    const element = elements[elementKey];
but don't we need that const element to store the mapping of "report a problem option"  that is connected to feature file --**Then I select the "report a problem option" from the contact dropdown** ?

2023-02-13 18:26 UTC, ayan1229 commented on apps/oew/playwright/tests/click.spec.ts
> +    const element = elements[elementKey];
nevermind, I got it!

2023-02-13 18:33 UTC, samanthaandrews commented on apps/oew/playwright/tests/click.spec.ts
> +    const element = elements[elementKey];
Yup. In this specific case we are not passing in the contact dropdown element from Cucumber. But you could do that too if you wanted, and if that were the case then you would need to pass that parameter into the locator.

2023-02-14 13:57 UTC, Toxiapo approved these changes
Thanks! This looks great.

2023-02-14 15:05 UTC, merged

2023-02-14 15:14 UTC, samanthaandrews commented
Merging this PR was fine! The release PR is independent from anything in the `main` branch. This is a change from our previous release process. We will release whatever is in the current release branch before merging that branch back into `main`. We are no longer using a `production` branch for releases.

2023-02-14 15:16 UTC, kristojorg commented
Benefit of the new release branching process : )

2023-02-14 15:32 UTC, Toxiapo commented
Phew ok, thank you!! @kristojorg @samanthaandrews