Oe 811/skin settings page
NYPL/ereading-clients pull request #614
Opened 2023-02-23 21:49 UTC by oliviawongnyc

- OE-811(https://jira.nypl.org/browse/OE-811): Skin Settings wireframe with UI designs

2023-02-27 15:40 UTC, Toxiapo reviewed
This looks good to me! Just a couple of small comments.

2023-02-27 15:40 UTC, Toxiapo commented on apps/oeh/CHANGELOG.md
> +- OE-811: Skin Settings wireframe with UI designs
This is not a wireframe, so I think `Skin Settings with UI designs` is fine

2023-02-27 15:40 UTC, Toxiapo commented on apps/oeh/src/App.tsx
> +import "./styles/base";
This is much cleaner, nice!

2023-02-27 15:40 UTC, Toxiapo commented on apps/oeh/src/components/Header.tsx
> +const Header = ({ showBackButton = false }: { showBackButton?: boolean }) => {
Can you write a little comment on what this component does?

2023-02-27 15:40 UTC, Toxiapo commented on apps/oeh/src/icons/LiveHelp.tsx
> +  <IonIcon
Does this allow us to apply custom CSS(mostly colors and size) if needed?

2023-02-27 15:40 UTC, Toxiapo commented on apps/oeh/src/styles/settings.css
> +.settings ion-toolbar {
I think if we want to scope the CSS for a specific page, you can import it into the page component; it will automatically scope the styles. i.e `import '../styles/settings.css'` in the setting page

2023-03-01 14:13 UTC, oliviawongnyc commented on apps/oeh/src/icons/LiveHelp.tsx
> +  <IonIcon
Yes! Can pass as props.

2023-03-01 14:18 UTC, oliviawongnyc commented on apps/oeh/src/styles/settings.css
> +.settings ion-toolbar {
Hmm, when I do that, I lose the two styles that I was losing before because of the ordering: text size and padding.

2023-03-02 12:55 UTC, Toxiapo commented on apps/oeh/src/styles/settings.css
> +.settings ion-toolbar {
OK, let's just keep it this way until we can come up with a better solution.

2023-03-02 13:12 UTC, Toxiapo commented
The failed CI is an [ongoing issue](https://github.com/vitejs/vite/issues/2433) with vite build. 

I think for now, we can try to increase the space for the build command i.e.`"build": "NODE_OPTIONS=--max-old-space-size=8192 vite build"`

@kristojorg pjr may need this aswell

2023-03-02 14:08 UTC, kristojorg commented
Interesting, thanks for the heads up @Toxiapo : )

2023-03-04 17:06 UTC, Toxiapo requested changes
Just one last thing then we can merge this!

2023-03-06 20:15 UTC, oliviawongnyc commented on apps/oeh/src/components/Settings/SignOut.tsx
> +import { Logout } from "icons";
Done!

2023-03-06 21:56 UTC, Toxiapo approved these changes
LGTM!

2023-03-06 21:58 UTC, Toxiapo commented
@oliviawongnyc @samanthaandrews I think we should ask Jen to VQA this, but I am not sure she's set up to test these builds on the phone. The web version is not suitable for VQA because it's platform specific.

2023-03-06 22:08 UTC, oliviawongnyc commented
> @oliviawongnyc @samanthaandrews I think we should ask Jen to VQA this, but I am not sure she's set up to test these builds on the phone. The web version is not suitable for VQA because it's platform specific.

@To

2023-03-06 22:09 UTC, oliviawongnyc commented
> @oliviawongnyc @samanthaandrews I think we should ask Jen to VQA this, but I am not sure she's set up to test these builds on the phone. The web version is not suitable for VQA because it's platform specific.

@Toxiapo will hold off on merging until we determine how to VQA. I wonder if it's worth setting her up with the repo and the emulator?!

2023-03-07 18:02 UTC, samanthaandrews commented
> > @oliviawongnyc @samanthaandrews I think we should ask Jen to VQA this, but I am not sure she's set up to test these builds on the phone. The web version is not suitable for VQA because it's platform specific.
> 
> @Toxiapo will hold off on merging until we determine how to VQA. I wonder if it's worth setting her up with the repo and the emulator?!

I have "Figure out QA for hybrid apps" on my to do list this week! But it will probably take me a while to develop that plan. In the meantime, I am wondering if screenshots would suffice for these upcoming PRs? We could add Android and iOS screenshots to the Jira ticket and tag Jennifer to review them there.

2023-03-07 18:25 UTC, Toxiapo commented
@samanthaandrews that sounds good to me! Screenshots or small videos

2023-03-20 19:51 UTC, merged