[WIP] OE-795: Add Clever auth
NYPL/ereading-clients pull request #616
Opened 2023-02-24 23:58 UTC by Toxiapo

2023-02-25 16:38 UTC, Toxiapo commented on apps/oeh/ios/App/App/Info.plist
> +				<string>OpenEbooks</string>
We need a custom URI for native apps

2023-02-28 19:59 UTC, Toxiapo commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
@ettore For the redirect to work, I had to add a custom URI so that the app knows where to redirect. This is working fine for ios >= 13, relogging the second time is also fine. I think there was a concern about security risks with using a custom URL scheme but I am not sure what that really means and if that's a concern when you were implementing the clever flow? afaik, companies like airbnb, bestbuy uses custom URL as well. cc. @samanthaandrews  @kristojorg

2023-02-28 20:05 UTC, Toxiapo commented on apps/oeh/android/app/src/main/res/values/strings.xml
> -    <string name="custom_url_scheme">org.openebooks.app</string>
@roywatson I am curious what your thought on custom URLs for android and if you had experience with it.

2023-02-28 22:27 UTC, ettore commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
ideally Universal Links should be used instead of custom URLs.  They are newer, more secure and per Apple it's the preferred way of deep linking:
https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app

The security risk for custom url schemes is that different apps could register the same url schemes. Since deep linking with custom URL schemes is all done client-side, it could lead to wrong redirection and other hacks.  See this note in the doc above:

> "If multiple apps register the same scheme, the app the system targets is undefined. There’s no mechanism to change the app or to change the order apps appear in a Share sheet."

Universal Links have a server side component in the flow that prevents that. That's what we did when we re-did the auth flow for OE native last year.  Setting up universal links was a little painful but the app is set up now, and if we keep the same AppID it should continue to work. 

Here are some more articles about the differences between the two:
https://stackoverflow.com/a/45533475/238983

https://medium.com/wolox/ios-deep-linking-url-scheme-vs-universal-links-50abd3802f97

More explanation on how UL work (I think this was my reference when I did the work):
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

2023-03-01 18:17 UTC, Toxiapo commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
Thank you for the links and info! @ettore It seems like Ionic also suffers from the[ redirect problem ](https://github.com/ionic-team/capacitor-plugins/issues/675#issuecomment-957760081)with the universal links you mentioned on the ticket. The in-app browser uses `SFSafariViewController` by default.

I would like to set this up the right way if possible, but I am having difficulties getting the universal link to run. Do you think I can put up some time on your calendar to go over this?

2023-03-01 18:39 UTC, ettore commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
definitely... I'll need to review how this works in the details because it's been a while 😅 

if I remember well SFSafariViewController is also what I used, and one thing I didn't try was using a WKWebView, which provides more control. Is there a way to control how the web page is opened in the in-app browser in capacitor?

2023-03-01 19:26 UTC, Toxiapo commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
Thank you!

The package I am using here is @capcitor/browser, which uses SFSafariViewController I don't think I can change that. There's an [alternative plugin](https://github.com/apache/cordova-plugin-inappbrowser) that uses WKWebView but it's not being maintained, unfortunately...

2023-03-01 20:51 UTC, Toxiapo commented
Converting this back to Draft while I meet with Ettore on the Universal Link

2023-03-02 11:31 UTC, kristojorg commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
Just dropping a note - if this requires a server side component and we don't want to change the CM, we could use the API routes at openebooks.org pretty easily.

2023-03-02 17:15 UTC, ettore commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
btw all I meant with "server side component" was that the `/.well-known/apple-app-site-association` file that needs to be present. For the current production apps we have:

https://librarysimplified.org/.well-known/apple-app-site-association

So I think we should be able to reuse this one. We can also move it to a new domain and simply refer to that.

2023-03-02 18:11 UTC, ettore commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
I reread the [UL docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html) and I forgot that to implement this there's a native part as described there. So we need to explore what we can do with Capacitor.

2023-03-02 18:43 UTC, Toxiapo commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
Seems like the server URL should match the `appID` we set in the `[capacitor.config.ts](https://github.com/NYPL/ereading-clients/blob/39e991976e2db536d2e0e2aac7ef0a7f1e914dd6/apps/oeh/capacitor.config.ts#L7)` file. If we want to continue using `librarysimplifed`, we might need to update our `appId` to something like `org.librarysimplified.OpenEbook`. Is this ok for us to do?  @kristojorg @kristojorg

2023-03-02 18:58 UTC, ettore commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
so, the appID (which is really the bundleID, Capacitor is confusing the 2 things here) should not change because that's used by the apple ecosystem to identify the app in the App Store. However, we can change the rest: both the domain that hosts the `apple-app-site-association` resource, its contents, as well as how we refer to it (the "associated domain") from Xcode as described in the [apple docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html). 
Is there documentation about universal links and capacitor maybe? If we can't add native code we'll need to pass thru capacitor somehow.

2023-03-02 19:26 UTC, Toxiapo commented on apps/oeh/ios/App/App/Info.plist
> +        </dict>
Yes, the [capacitor doc ](https://capacitorjs.com/docs/guides/deep-links#ios-configuration) never mentioned the appID to be associated with the hosting domain, so I am guessing we could just define the associated domain ourselves.

2023-03-10 00:53 UTC, ettore commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_ENTITLEMENTS = "Open eBooks.entitlements";
These are a little odd because they appear to be on the `Pods-Open eBooks` configuration but I'm not sure how.... did you do these changes explicitly or was it Xcode?

2023-03-10 14:34 UTC, Toxiapo commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_ENTITLEMENTS = "Open eBooks.entitlements";
I don't think I have touched that file so it could be Xcode

2023-03-10 14:39 UTC, Toxiapo commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_ENTITLEMENTS = "Open eBooks.entitlements";
would this affect our build? I can remove this line and try if can build the app locally.

2023-03-10 19:09 UTC, ettore commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_ENTITLEMENTS = "Open eBooks.entitlements";
I checked out your branch and I think _some_ of these changes are not necessary. This one for CODE_SIGN_ENTITLEMENTS is needed because this is how we get applinks to work.

I'll comment on the others explicitly to avoid confusion.

I also figured out where in Xcode we can see these changes -- that's the part I could not understand from the PR (because of Xcode cryptic project file format).

2023-03-10 19:25 UTC, ettore commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
to see these changes in Xcode you should click on the "App" project on the far left where the source files are. Then click on the Open eBooks target and "Build Settings". Scroll down to Signing and you should see something like this:

<img width="1188" alt="xcodebuildsettings" src="https://user-images.githubusercontent.com/289104/224405216-47bbcb9c-71ce-4b10-a6d7-8b0d1291ca56.png">

This "Levels" view shows you how Xcode applies build settings, which is kinda like CSS, that is in increasingly specific layers; so from right to left we have:
- defaults layer (unchangeable, Xcode factory defaults)
- project layer (settings affecting the whole project, overriding the defaults)
- config files layer (.xcconfig files such as our `Pods-Open eBooks.debug.xcconfig` file are editable and are the foundation of targets; they override the project's)
- target layer (settings affecting an app's build directly, overriding the config files)

So for example any settings at target layer overrides anything else. 

As you can see the customization for "Provisioning Profile" (which corresponds to PROVISIONING_PROFILE_SPECIFIER in the project source)  is unneeded because it's the same as the Project. If you select it and press the Delete key it will remove it and the app will build the same.

Same reasoning for the Code Signing style (CODE_SIGN_STYLE): unneeded duplicated customization.

For CODE_SIGNING_IDENTITY, can you see what happens if you keep the project default "iOS Developer"?  You can also do the same trick here, since the default is in fact "iOS Developer". I changed and it still built. It would be good to keep the same code signing identity.

Another way to do all this is to manually edit the project file in a text editor, but I thought it would be good to show how these settings translate on the UI. Let me know if you want to pair on this, I'm available.

2023-03-10 21:28 UTC, Toxiapo commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_IDENTITY = "Apple Development";
Thanks! This is helpful.

2023-03-18 01:42 UTC, Toxiapo commented on apps/oeh/README.md
> +
@MalcolmMcFly I added this instruction for local development. I believe this is all we need?

2023-03-20 21:15 UTC, samanthaandrews requested changes
Just a few small things regarding the xcode changes. this was a ton of work and it looks really good.

2023-03-20 21:15 UTC, samanthaandrews commented on apps/oeh/src/pages/sign-in/clever/callback.tsx
> +    validateAndRedirect(window?.location?.hash, setCredentials, history);
why do we run `validateAndRedirect` twice?

2023-03-20 22:46 UTC, Toxiapo commented on apps/oeh/src/pages/sign-in/clever/callback.tsx
> +    validateAndRedirect(window?.location?.hash, setCredentials, history);
Good catch, we don't need two.

2023-03-20 22:47 UTC, Toxiapo commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
I removed these, but then it came back after building the app...

2023-03-21 14:15 UTC, samanthaandrews commented on apps/oeh/ios/App/App.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Ok, that's fine. I am currently talking with Appflow support so they can help me understand what these files are supposed to include, so I'm not going to worry about it until they tell me what these values should be!

2023-03-21 14:18 UTC, samanthaandrews commented on apps/oeh/src/lib/auth/index.tsx
> +export const validateAndRedirect = (
nice!

2023-03-21 14:19 UTC, samanthaandrews approved these changes

2023-03-21 15:50 UTC, MalcolmMcFly commented on apps/oeh/README.md
> +
Yes this is good.

2023-03-22 11:27 UTC, kristojorg commented on apps/oeh/android/app/src/main/res/values/strings.xml
> -    <string name="custom_url_scheme">org.openebooks.app</string>
I honestly don't remember adding this but it's possible I did?

2023-03-22 12:38 UTC, Toxiapo commented on apps/oeh/android/app/src/main/res/values/strings.xml
> -    <string name="custom_url_scheme">org.openebooks.app</string>
OK! I think this is fine because we don't use these values.

2023-03-22 12:39 UTC, merged

2023-03-23 09:40 UTC, kristojorg commented on apps/oeh/src/pages/sign-in/SignIn.tsx
> +      console.info("Getting the url from the appUrlOpen listenerer.", cleanUrl);
Stray console

2023-03-23 09:44 UTC, kristojorg approved these changes
This looks great! And seems to work great too : )

It's a complicated feature and I have a bit of trouble tracing the flow through the various files myself. It might be worthwhile to write a little description of the process in the README. Like a high level, "these are the steps" kind of thing.

2023-03-23 15:09 UTC, Toxiapo commented
> This looks great! And seems to work great too : )
> 
> It's a complicated feature and I have a bit of trouble tracing the flow through the various files myself. It might be worthwhile to write a little description of the process in the README. Like a high level, "these are the steps" kind of thing.

Good idea!