OE-810: Skin onboarding
NYPL/ereading-clients pull request #624
Opened 2023-03-06 22:53 UTC by Toxiapo

2023-03-06 22:54 UTC, Toxiapo commented on apps/oeh/src/chakra/theme/index.ts
> +});
I created this theme for OEH to rest some of the global styles.

2023-03-06 22:56 UTC, Toxiapo commented on apps/oeh/src/components/Header.tsx
> -  }, [prefersDark]);
@oliviawongnyc I moved this and created a hook from it, I needed to check the color mode for the sign-in page as well.

2023-03-06 22:59 UTC, Toxiapo commented on apps/oeh/src/main.tsx
> +        <ChakraProvider theme={baseTheme} resetCSS={false}>
This is to turn off the reset CSS that's being injected in the header from Chakra. This includes removing the default HTML styles for semantic tags like headings, p, a, etc. If we need to bring this back, we should do it in the ionic CSS.

2023-03-06 23:02 UTC, Toxiapo commented on apps/oeh/src/pages/Settings.tsx
> -      </IonPage>
I am unsure why we have a first book sign-in form on the settings page. I think we should just redirect the user to the sign-in page instead.

I also think that the "My books" page should also perform a auth redirect. Currently, it shows a "You are not signed in" message. But let me know what you all think!

2023-03-06 23:04 UTC, Toxiapo commented on apps/oeh/src/styles/variables.css
> +  --zindex-tooltip: 1800;
I copied this from our chakra/theme folder; it would be easier for us to work with variables instead of random digits.

2023-03-06 23:06 UTC, Toxiapo commented on apps/oeh/src/styles/variables.css
> +  --zindex-tooltip: 1800;
This should probably be a `zindex.css` file too... for discoverability.

2023-03-07 15:46 UTC, Toxiapo commented on apps/oeh/src/components/UserAgreement.tsx
> +      <p>Last Updated: 05/01/2016</p>
This page has the same exact copy from https://www.openebooks.org/app-user-agreement

2023-03-08 15:07 UTC, oliviawongnyc requested changes
Looks sooooo good! And thank you for all that great work you did to share code and styles. You've set us up well for moving forward!

2023-03-08 15:41 UTC, samanthaandrews commented on apps/oeh/src/components/FirstbookForm.tsx
> +    const pin = e.detail.value?.replace(/\D/g, "") ?? "";
I do think these questions should be answered in a meeting/conversation with Jen!

2023-03-08 15:53 UTC, samanthaandrews reviewed
Just a couple small things from me! I do think sitting down briefly with Jen & @oliviawongnyc to make sure everyone's on the same page about error handling for sign in is a good idea. It's the first time we're explicitly asking for error handling designs so there will be some good discussion about what devs can do versus what design is thinking about.

2023-03-08 15:53 UTC, samanthaandrews commented on apps/oeh/src/components/FirstbookForm.tsx
> +  const codeChange = (e: CustomEvent<InputChangeEventDetail>) => {
Let's rename this to `accessCodeChange` for clarity

2023-03-08 15:53 UTC, samanthaandrews commented on apps/oeh/src/components/FirstbookForm.tsx
> +  const shouldDisableBtn = containsError || !formFilled;
let's rename this to `buttonIsDisabled`

2023-03-08 15:53 UTC, samanthaandrews commented on apps/oeh/src/components/UserAgreement.tsx
> +      <p>Last Updated: 05/01/2016</p>
We will eventually turn this into a shared package so that we don't duplicate content, but for now this is fine!

2023-03-08 16:54 UTC, Toxiapo commented on apps/oeh/src/components/FirstbookForm.tsx
> +    const pin = e.detail.value?.replace(/\D/g, "") ?? "";
Good idea, I will set up a meeting.

Re: Do we really want to not allow users to type letters into the PIN input? 

I should take out that regex rule because we don't need it anymore. Per Jen's request, the Pin field should show the number keyboard, hence I set the type to `"tel"`. If we run the app on a device, the input keyboard wouldn't show letter keys.

2023-03-08 21:50 UTC, Toxiapo commented on apps/oeh/src/components/FirstbookForm.tsx
> +    if (resp.status === 401) {
Yeah, this is something I should confirm with Jen as well. The API doesn't tell us which one was correct so we will have to either take the errors out from the input or put it elsewhere.

2023-03-08 21:51 UTC, Toxiapo commented on apps/oeh/src/styles/settings.css
> +.settings .help-card ion-button::part(native) {
OHH it must be a wrong read on the value. I will update this.

2023-03-08 21:54 UTC, Toxiapo commented on apps/oeh/src/components/FirstbookForm.tsx
> +          type="tel"
This is so that it shows the number-only keyboard on a mobile device.

2023-03-08 21:57 UTC, Toxiapo commented on apps/oeh/src/components/FirstbookForm.tsx
> +      <IonButton type="submit" expand="block" disabled={shouldDisableBtn}>
It is using #50555C. I think it could be that Ionic has an `opacity: .5` set for disabled buttons. I will remove that.

2023-03-08 21:59 UTC, Toxiapo commented on apps/oeh/src/hooks/useColorMode.ts
> +  return [isDarkMode];
Good catch. It should be just a boolean. Updated.

2023-03-08 22:08 UTC, Toxiapo commented on apps/oeh/src/pages/sign-in/SignIn.tsx
> +        <FooterLinks>
I see some frames with extra spacings. I will remove them for now and ask Jen what she thinks.

2023-03-08 22:42 UTC, Toxiapo commented on apps/oeh/src/styles/variables.css
> +  --zindex-tooltip: 1800;
I think we should do that for all the commonly used values. I will make a follow-up ticket.

2023-03-20 16:09 UTC, Toxiapo commented on apps/oeh/src/pages/sign-in/firstbook/FirstbookPage.tsx
> +      <Header showBackButton />
Did you land on this page via a restart? I think it's because the "back" button relies on the browsing history, and if it can't find it, it will not show the button.

2023-03-20 18:00 UTC, Toxiapo commented
> Oooh also there should be that error message that appears when authentication fails, but I think we may still be waiting on Jen for that copy and placement.

Yes! Jen is working on that.

2023-03-23 17:40 UTC, oliviawongnyc commented on apps/oeh/src/components/Header.tsx
> +      <IonToolbar color="secondary" mode="ios">
@Toxiapo I'm still curious about this

2023-03-23 17:41 UTC, oliviawongnyc approved these changes
I think this looks good! Nice that Ionic has a maxLength for the input. Did we want to add 10 for the maxLength of the Access Code? I forget. Also, did we decide not to add a "Please enter valid PIN" message if the user types letters instead of numbers? We have had a lot of back and forth on this so I think this is one of those things we move forward with and fix later if Jen has more feedback.

2023-03-24 20:19 UTC, Toxiapo commented
> I think this looks good! Nice that Ionic has a maxLength for the input. Did we want to add 10 for the maxLength of the Access Code? I forget. Also, did we decide not to add a "Please enter valid PIN" message if the user types letters instead of numbers? We have had a lot of back and forth on this so I think this is one of those things we move forward with and fix later if Jen has more feedback.

Right, we decided not to set the length for the access code because we are not sure what's the constraints for the field

2023-03-28 18:44 UTC, merged