OE-881: Add splash screen and icons
NYPL/ereading-clients pull request #634
Opened 2023-03-22 19:53 UTC by Toxiapo

2023-03-22 21:42 UTC, Toxiapo commented
Hi @russellcullen, I've noticed that on Android 12 and above, the launch screen image is rendered from the mipmap folder, whereas for versions 11 and below, the icon from the drawable folders is used instead. Can you please confirm if this behavior is expected or if there is a configuration option available to use the same resource for both versions, if desirable? 

Additionally, I have separate icon designs for night and light modes, and I have included the night folder for both mipmaps and drawable. Though, this has resulted in a large number of images for the app. Do you think this is OK or can we reduce the number of resources? AFAIK, the minimum android we support is Android 6. Thanks!

2023-03-22 21:53 UTC, russellcullen commented
@Toxiapo I believe that is expected for the launch icon but I will double check and get back to you to be sure. 

And regarding the additional images, this should be ok as not all the resources get shipped to the end user. I believe we build the app using App Bundles, which ensures that only the resources needed for a particular device are bundled to the end user. 

That being said, both night and light mode images will be bundled for a particular density but nothing we can do about that. A bit of expected extra images we can't avoid

2023-03-22 21:53 UTC, Toxiapo commented on apps/oeh/ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
>      {
Hi @ErnestFan, would you mind helping me take a look at these settings and let me know if everything looks good, just making sure I am not breaking anything!

These icons were generated using a Capacitor plugin, they should support dark and light modes, for both the app icons and splash screens. thank you!

2023-03-23 12:28 UTC, Toxiapo commented on apps/oeh/ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
>      {
Sure! I will send it through slack.

2023-03-28 08:35 UTC, kristojorg requested changes
Just the one thing. Crazy how many icon files there are in an app!

2023-03-28 08:35 UTC, kristojorg commented on apps/oew/package.json
> +    "@nypl/opds": "^0.1.0-alpha.0",
This should be changed back to use the `"*"`

2023-03-28 20:45 UTC, Toxiapo commented on apps/oew/package.json
> +    "@nypl/opds": "^0.1.0-alpha.0",
Updated!

2023-03-29 16:21 UTC, samanthaandrews commented
it really is crazy how many icon files there are. thank you for doing this @Toxiapo !

2023-03-29 16:42 UTC, russellcullen commented on apps/oeh/android/app/src/main/res/drawable-v24/ic_baseline_add_24.xml
nitpick: is this file used? Might be safe to delete if not

2023-03-29 19:12 UTC, Toxiapo commented on apps/oeh/android/app/src/main/res/drawable-v24/ic_baseline_add_24.xml
Yup, the `activity_bookmarks.xml` config file is referencing it.

2023-03-29 19:35 UTC, russellcullen commented on apps/oeh/android/app/src/main/res/drawable-v24/ic_baseline_add_24.xml
I think this might be the same as the one in `drawable/ic_baseline_add_24.xml`, which will be used as a default if this file is missing. In theory this icon will be used on android versions 24+ (since its in `res/drawable-v24`), but if theres no difference then I dont think it's needed

2023-03-29 19:57 UTC, Toxiapo commented on apps/oeh/android/app/src/main/res/drawable-v24/ic_baseline_add_24.xml
ah yes, you are correct, they are the same! I am happy to remove this if it's a duplicate.

2023-03-30 16:00 UTC, russellcullen approved these changes

2023-04-01 14:10 UTC, kristojorg approved these changes
Looks good!

2023-04-03 12:36 UTC, merged